apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheusconfig
  labels:
    app: prometheusconfig
data:
  prometheus.yaml: |
    global:
     scrape_interval: 5s
     external_labels:
        monitor: 'server'
    scrape_configs:
      - job_name: csvserver
        static_configs:
           - targets:
           - csvserver: 192.168.166.11:9300
