apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2022-03-28T11:28:29Z"
  generation: 5
  labels:
    app: csvserver
  name: csvserver
  namespace: default
  resourceVersion: "9569"
  uid: 36261bc5-0dff-42e9-9b8d-f4c2330babfe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csvserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csvserver
    spec:
      containers:
      - image: infracloudio/csvserver:latest
        imagePullPolicy: Always
        name: csvserver
        ports:
        - containerPort: 9300
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csvserver/inputdata
          name: test-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/harsha/K8/inputFile
          type: ""
        name: test-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-28T11:45:12Z"
    lastUpdateTime: "2022-03-28T11:45:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-28T11:28:29Z"
    lastUpdateTime: "2022-03-28T12:29:11Z"
    message: ReplicaSet "csvserver-7f7b58cdb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
