apiVersion: v1
kind: Service
metadata:
  name: prometheusservice
spec:
  selector:
    name:  prometheus
  type: NodePort
  ports:
  - name:  prom
    port:  9090
    targetPort:  9090
    nodePort: 30909