apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.22.0
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus
              name: data
      volumes:
        - name: data
          configMap:
            name: prometheusconfig
